- hosts: databases
  var:
    password: DevOps@2020
    username: mylandmark
  tasks:
  - name: create username
    user: "{{username}}"
    state: present
  - name: install package
    package: ['wget', 'unzip']
    state: latest
  - name:
    debug:
      msg: "{{password}}"